### ISSUE TITLE
Rewrite in C++?

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#1]
Hey there,
There is a thing that I've been pondering about for quite some time, (since I'm still saving up to buy a Jeannie soon) and want to try myself at some point: It might be smart to rewrite the code in C++ (Should mostly be copying stuff over though) to utilize templates and other C++ features to vastly improve code readability and maybe debuggability by removing most of the repeating patterns currently required for the 8 voices this synth has.
What do you think?
Thanks for this wonderful and creative synth!

**Comment by rolfdegen** [comment]
I am sorry. I'm not a particularly good programmer. Coming from Arduino, I only know C. 
But I'm grateful for any help improving the code. Thanks :)

**Comment by UltraBlackLinux** [comment]
closing this because nobody asked lol
