### ISSUE TITLE
Bit crusher effect

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#12]
Hey there,
I just noticed, that I would really like to use a bitcrusher, could you implement that, if it doesn't exist already (I'm pretty sure)?
Thanks!

**Comment by rolfdegen** [comment]
I'm sorry. We have no bit crusher effect. But in the Oscillator menu (Sub page) there is a waveshaper. We switched the waveshaper behind the filters. The waveshaper has 13 curves and a gain controller. That gives a lot of room for distortion.

![Voice V1 40](https://user-images.githubusercontent.com/16689445/175767050-622fae6c-dd6b-4d23-8dd1-d8f642624767.PNG)

**Comment by UltraBlackLinux** [comment]
Okay, thanks for clearing that up :)

I will look further into that.
