### ISSUE TITLE
What changed

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#13]
Hey there,
I just noticed you pushed another update: 1.57
The problem that I am seeing is that I (and all other users) don't know, what changed, since there is no changelog, no updates in the releases tab, the codebase here on github is 4 months old and all the source zips got deleted.
What changed? And why no updates to the code? I would love to try out what's new.
Thanks!

**Comment by rolfdegen** [comment]
Hallo Linux
A small bug when saving patches. The SYN parameter was not saved correctly in the LFOs.
The following files have been changed
Jeannie.ino
ST7735Display.h

**Comment by UltraBlackLinux** [comment]
> Hallo Linux A small bug when saving patches. The SYN parameter was not saved correctly in the LFOs. The following files have been changed Jeannie.ino ST7735Display.h

Oh awesome, thanks :)
(Feel free to close issues)

**Comment by UltraBlackLinux** [comment]
Could you upload the code changes to this repo again?
