### ISSUE TITLE
Pitchwheel affects running sequencer instead of midi notes

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#20]
Hey there,
I just discovered another issue: Using the pitch wheel while the sequencer is running actually pitch-shifts the sequencer and not just the midi notes.
Is this intentional?
Thanks!

**Comment by rolfdegen** [comment]
PitchWheel transposes both. Midi notes and sequencer notes.

**Comment by UltraBlackLinux** [comment]
... that is in fact correct. I just checked and can't reproduce this. No clue how this happened in the first place

**Comment by rolfdegen** [comment]
Jeannie does not receive midi notes from Reaper. What am I doing wrong ?

**Comment by rolfdegen** [comment]
OK. It works now. Here is an example of JingleBell in Peaper.

[JingleBells.zip](https://github.com/rolfdegen/Jeannie-Open-source-Synthesizer/files/9541224/JingleBells.zip)

**Comment by rolfdegen** [comment]
OK. I understand your problem now. There are problems with the PitchWheel modulation. Did you record the PichWheel modulation in Reapeat via Midi or draw it in Reaper?

**Comment by rolfdegen** [comment]
OK. I tested it with my Blofeld and it works fine. I will solve the problem in my Jeannie.

**Comment by UltraBlackLinux** [comment]
> OK. I understand your problem now. There are problems with the PitchWheel modulation in Reaper. Did you record the PichWheel modulation in Reapeat via Midi or create it in Reaper?

I previously did that just with the pitch wheel.

I didn't try it in Reaper yet, but there are two ways: The ReaControlMidi vst plugin (click the FX button), and directly recording the pitchwheel into the midi track and playing it back.
