### ISSUE TITLE
Compiling V1.57

### ISSUE THREAD

**Issue by Wladimir25** [rolfdegen/Jeannie-Open-source-Synthesizer#23]
Hello Rolf,
I tried to compile the V1.57 but got some errors, 

In ST7735Display.h
myControlChange() was not declared in this scope
updateFilterFM() was not declared in this scope
updateFilterFM2() was not declared in this scope
recallPatch() was not declared in this scope
setWave... () was not declared in this scope
What am I doing wrong?

Which Library for #include <Mcp320x.h> do you use?

Is that right?
Board: "Teensy 4.1"
USB Type: "Serial + MIDI" or   USB Type: "Serial + MIDI" + Audio?
CPU Speed "720 MHz (overclock)"?
Optimize: "Faster"?

Thank you very much
Andreas

**Comment by rolfdegen** [comment]
I think your compiler didn't do the prototype declaration automatically in ST7735Display.h . You have to add them manually.

**Comment by Wladimir25** [comment]
Thank you, that was the problem.
