### ISSUE TITLE
V1.93: Effects seemingly not applied

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#25]
Hey there,
I just noticed an issue in version V1.93: The effects don't seem to work anymore. I even tried a stock preset (AL BIG), which had the chorus enabled. Even if it's toggled between states, no difference can be heard.
Can anyone reproduce this?
Thanks!

**Comment by rolfdegen** [comment]
Its a new Firmware Version 1.99
