### ISSUE TITLE
Mass storage mode

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#26]
Hey there,
I don't often disassemble my Jeannie or ever want to really, but accessing the SD card is sadly not possible any other way.
Could you add support for a USB mass storage mode so the Jeannie SD appears like a USB stick? I have seen projects for the teensy trying to do exactly that, maybe that could be implemented?
Thanks!

**Comment by rolfdegen** [comment]
Sorry, that doesn't work. For this reason I have integrated SysEx Dump. This allows you to load a patch or patch bank via USB or send it to the PC/MAC.
________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Mittwoch, 1. Februar 2023 20:29
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [rolfdegen/Jeannie-Open-source-Synthesizer] Mass storage mode (Issue #26)


Hey there,
I don't often disassemble my Jeannie or ever want to really, but accessing the SD card is sadly not possible any other way.
Could you add support for a USB mass storage mode so the Jeannie SD appears like a USB stick? I have seen projects for the teensy trying to do exactly that, maybe that could be implemented?
Thanks!

**Comment by UltraBlackLinux** [comment]
This does not give access to the splashes folder, which I had some fun with yesterday
