### ISSUE TITLE
Code Explanation

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#4]
Hey there,
I'm currently preparing to rework some parts of the code for when I'm soon receiving my Jeannie, but I am having trouble understanding some parts of the code, so I'm seeking your help here and in the comments below.
The first thing that I want to rework is AudioPatching.h.
I have already understood that there is stuff for all 8 voices, but what are A/B supposed to mean? Left/Right for Stereo?
There are also some inconsistencies that I can't wrap my head around:
```cpp
AudioConnection          patchCord351(pwmLfoA, 0, pwMixer1a, 0); //A connected to A
AudioConnection          patchCord359(pwmLfoA, 0, pwMixer1b, 0); // and B to B, as expected

AudioConnection          patchCord251(waveformMod1a, 0, oscModMixer1b, 3); //A connected to B?
AudioConnection          patchCord259(waveformMod1b, 0, oscModMixer1a, 3); // B to A?

AudioConnection          patchCord351(pwmLfoA, 0, pwMixer1a, 0); //LFOA connected to A
AudioConnection          patchCord359(pwmLfoA, 0, pwMixer1b, 0); //LFOA connected to B ...  They are connected in an alternating pattern, where LFOB is connected to pwMixer2a and B, but LFOA to 3a and b -- LFOB is not used anywhere else, I am so massively confused
```
Please explain, I don't get it.
Thanks!
(Please keep this open, there is probably more stuff that I won't understand)

**Comment by rolfdegen** [comment]
Hallo user

Thank you for your support 🙂  Here is the current original audio patch for a voice in Jeannie.
There are still a few small changes I need to draw.

Greetings Rolf
________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Montag, 18. April 2022 14:54
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [rolfdegen/Jeannie-Open-source-Synthesizer] Code Explanation (Issue #4)


Hey there,
I'm currently preparing to rework some parts of the code for when I'm soon receiving my Jeannie, but I am having trouble understanding some parts of the code, so I'm seeking your help here and in the comments below.
The first thing that I want to rework is AudioPatching.h.
I have already understood that there is stuff for all 8 voices, but what are A/B supposed to mean? Left/Right for Stereo?
There are also some inconsistencies that I can't wrap my head around:

AudioConnection          patchCord351(pwmLfoA, 0, pwMixer1a, 0); //A connected to A
AudioConnection          patchCord359(pwmLfoA, 0, pwMixer1b, 0); // and B to B, as expected

AudioConnection          patchCord251(waveformMod1a, 0, oscModMixer1b, 3); //A connected to B?
AudioConnection          patchCord259(waveformMod1b, 0, oscModMixer1a, 3); // B to A?

AudioConnection          patchCord351(pwmLfoA, 0, pwMixer1a, 0); //LFOA connected to A
AudioConnection          patchCord359(pwmLfoA, 0, pwMixer1b, 0); //LFOA connected to B ...  They are connected in an alternating pattern, where LFOB is connected to pwMixer2a and B, but LFOA to 3a and b -- LFOB is not used anywhere else, I am so massively confused

**Comment by UltraBlackLinux** [comment]
> Hallo user Thank you for your support  Here is the current original audio patch for a voice in Jeannie. There are still a few small changes I need to draw. Greetings Rolf

Hey, I can't see what you are trying to show me, if this is an email-attachment, github might have filtered it, I have no idea.

**Comment by rolfdegen** [comment]
Hallo user

Unfortunately, the zip file was too big. I uploaded it to Github in the firmware folder "MC Projekt file".

Greetings from Germany. Rolf

________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Montag, 18. April 2022 16:28
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Rolf Degen ***@***.***>; Comment ***@***.***>
Betreff: Re: [rolfdegen/Jeannie-Open-source-Synthesizer] Code Explanation (Issue #4)


Hallo user Thank you for your support Here is the current original audio patch for a voice in Jeannie. There are still a few small changes I need to draw. Greetings Rolf

Hey, I can't see what you are trying to show me, if this is an email-attachment, github might have filtered it, I have no idea.

**Comment by UltraBlackLinux** [comment]
Well it seems like I will have to give up on my attempt to edit this project. Missing libraries, compilation errorrs, ...
I am just unable to even compile the version you sent me without any changes.
Not only this, but there are already only a few Arduino development tools and even less teensy tools, so it's a pain in itself to even work on this.
I doubt I will have any success modifying this with these problems.

**Comment by rolfdegen** [comment]
Someone reports that there are problems with the installed Teensyduino audio lib. Here is my installed audio lib for Jeannie.
[Audio.zip](https://github.com/rolfdegen/Jeannie-Open-source-Synthesizer/files/8511345/Audio.zip)

**Comment by rolfdegen** [comment]
Hallo user

Someone reports that there are problems with the installed Teensyduino audio lib. my installed audio lib for Jeannie.

Someone reports that there are problems with the installed Teensyduino audio lib. I uploaded my installed audio lib for Jeannie to Github.

Greeting Rolf
________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Montag, 18. April 2022 17:26
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Rolf Degen ***@***.***>; Comment ***@***.***>
Betreff: Re: [rolfdegen/Jeannie-Open-source-Synthesizer] Code Explanation (Issue #4)


Closed #4<https://github.com/rolfdegen/Jeannie-Open-source-Synthesizer/issues/4>.

**Comment by rolfdegen** [comment]
Hallo user

This is the current Jeannie source code for teensyduino.

Greetings Rolf
________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Montag, 18. April 2022 17:26
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Rolf Degen ***@***.***>; Comment ***@***.***>
Betreff: Re: [rolfdegen/Jeannie-Open-source-Synthesizer] Code Explanation (Issue #4)


Well it seems like I will have to give up on my attempt to edit this project. Missing libraries, compilation errorrs, ...
I am just unable to even compile the version you sent me without any changes.
Not only this, but there are already only a few Arduino development tools and even less teensy tools, so it's a pain in itself to even work on this.
I doubt I will have any success modifying this with these problems.

**Comment by UltraBlackLinux** [comment]
> Hallo user This is the current Jeannie source code for teensyduino. Greetings Rolf [Jeannie teensyduino.zip](https://github.com/rolfdegen/Jeannie-Open-source-Synthesizer/files/8530171/Jeannie.teensyduino.zip)

It still refuses, sadly. I give up. Arduino development is such a pain - Probably because it has somewhat of a nieche use case.

Teensy development seems to be even worse, as there are yet again less platforms supporting that as well. In the end you have like two options: Use the Patched arduino IDE, or use some other ide that supports teensy ootb.

**Comment by rolfdegen** [comment]
I will adapt it for Arduino and let you know.

Greetings Rolf

________________________________
Von: UltraBlackLinux ***@***.***>
Gesendet: Montag, 18. April 2022 17:26
An: rolfdegen/Jeannie-Open-source-Synthesizer ***@***.***>
Cc: Rolf Degen ***@***.***>; Comment ***@***.***>
Betreff: Re: [rolfdegen/Jeannie-Open-source-Synthesizer] Code Explanation (Issue #4)


Well it seems like I will have to give up on my attempt to edit this project. Missing libraries, compilation errorrs, ...
I am just unable to even compile the version you sent me without any changes.
Not only this, but there are already only a few Arduino development tools and even less teensy tools, so it's a pain in itself to even work on this.
I doubt I will have any success modifying this with these problems.
