### ISSUE TITLE
Remember knob rotation

### ISSUE THREAD

**Issue by UltraBlackLinux** [rolfdegen/Jeannie-Open-source-Synthesizer#8]
Hey there,
there is also a "problem" that I noticed, which has been somewhat disorienting at times: Switching menus does not remember the knob rotation. This leads to confusion when entering a menu, touching a menu knob and then losing the current option since it jumps to somewhere unexpected.
Can this be implemented?
Thanks!

**Comment by rolfdegen** [comment]
In version 1.56 there is a pickup function for the pots. It only works for filter and envelope adjustment.

**Comment by UltraBlackLinux** [comment]
works awesome! Thank you! Less disorienting now \:)
